(()=>{"use strict";
const $=s=>document.querySelector(s),status=$("#obs-status"),app=$("#obs-app"),gate=$("#signed-out"),list=$("#observation-list"),form=$("#obs-form"),photo=$("#photo"),photoName=$("#photo-name");
let observations=[],filter="all";
const say=m=>status.textContent=m||"";
async function api(path,options={}){const r=await fetch("/api/"+path,{credentials:"same-origin",...options,headers:{"content-type":"application/json",...(options.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Object.assign(new Error(d.error||"Service unavailable."),{status:r.status});return d}
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function localDate(v){const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(d)}
function render(){let rows=observations;if(filter==="favorite")rows=rows.filter(x=>x.favorite);if(filter==="pinned")rows=rows.filter(x=>x.pinned);if(!rows.length){list.innerHTML='<div class="empty">No observations here yet. Record your next night under the stars.</div>';return}
list.innerHTML=rows.map(o=>`<article class="obs-card ${o.pinned?"pinned":""}" data-id="${esc(o.id)}">
${o.hasPhoto?`<img class="obs-photo" src="/api/observation-photo/${encodeURIComponent(o.id)}" alt="Observation photo for ${esc(o.objectName)}" loading="lazy">`:""}
<div class="obs-body"><div class="obs-top"><div><h3 class="obs-title">${esc(o.objectName)}</h3><p class="obs-date">${esc(localDate(o.observedAt))}</p></div><div class="obs-actions"><button class="icon-button ${o.favorite?"active":""}" data-action="favorite" title="Favorite" type="button">★</button><button class="icon-button ${o.pinned?"active":""}" data-action="pinned" title="Pin" type="button">⌖</button></div></div>
<div class="obs-meta">${o.location?`<span class="chip">⌖ ${esc(o.location)}</span>`:""}${o.conditions?`<span class="chip">◌ ${esc(o.conditions)}</span>`:""}</div><p class="obs-notes">${esc(o.notes)}</p><button class="delete" data-action="delete" type="button">DELETE ENTRY</button></div></article>`).join("")}
async function load(){const d=await api("observations");observations=d.observations||[];render()}
async function imageData(file){if(!file)return null;if(file.size>12000000)throw Error("Choose a photo smaller than 12 MB.");const bitmap=await createImageBitmap(file),max=1280,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext("2d").drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return canvas.toDataURL("image/jpeg",.78)}
photo.addEventListener("change",()=>photoName.textContent=photo.files[0]?.name||"Choose your astronomy photo");
form.addEventListener("submit",async e=>{e.preventDefault();const button=$("#save-observation");button.disabled=true;say("Saving observation…");try{const payload={objectName:$("#object-name").value,observedAt:$("#observed-at").value,location:$("#location").value,conditions:$("#conditions").value,notes:$("#notes").value};const created=await api("observations",{method:"POST",body:JSON.stringify(payload)});if(photo.files[0]){say("Uploading observation photo…");const image=await imageData(photo.files[0]);await api("observation-photo/"+encodeURIComponent(created.id),{method:"POST",body:JSON.stringify({image})})}form.reset();photoName.textContent="Choose your astronomy photo";$("#observed-at").value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);await load();say("Observation saved to your Orbonix Account.")}catch(err){say(err.message)}finally{button.disabled=false}});
list.addEventListener("click",async e=>{const b=e.target.closest("[data-action]");if(!b)return;const card=b.closest("[data-id]"),id=card?.dataset.id,o=observations.find(x=>x.id===id);if(!o)return;try{if(b.dataset.action==="delete"){if(!confirm("Delete this observation?"))return;await api("observations/"+encodeURIComponent(id),{method:"DELETE"});observations=observations.filter(x=>x.id!==id)}else{const key=b.dataset.action,value=!o[key];await api("observations/"+encodeURIComponent(id),{method:"PATCH",body:JSON.stringify({[key]:value})});o[key]=value;observations.sort((a,b)=>Number(b.pinned)-Number(a.pinned)||String(b.observedAt).localeCompare(String(a.observedAt)))}render()}catch(err){say(err.message)}});
document.querySelectorAll(".filter").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");filter=b.dataset.filter;render()}));
(async()=>{try{const me=await api("me");gate.hidden=true;app.hidden=false;$("#observer-name").textContent=(me.user.firstName+" "+me.user.lastName).trim();$("#observed-at").value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);await load()}catch(err){if(err.status===401){app.hidden=true;gate.hidden=false;say("")}else say(err.message)}})();
})();